apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  value_from_values: {{ .Values.fruit }}
  value_from_chart: {{ .Chart.Name }}
  value_from_subchart: {{ .Subcharts.sample.Values.fruit }}
  files: {{ .Files.Get "files/new.txt" }}
  files1: {{ .Files.Glob "files/*.txt" }}
  files2: |
    {{ .Files.AsConfig "files/new.txt" }}


